

<!-- Box -->
				<div class="box">
					<!-- Box Head -->
					<div class="box-head">
						<h1 class="left">Reportes Planes Operativo.</h1>
					<br>
						<BR>
					</div>
					<!-- End Box Head -->	
                    
                    
					<!-- Table -->
					<div  style="min-height: 300px;">
						<table width="100%"  border="0" cellspacing="0" cellpadding="0">
						
						<tr>
								
						   <td>
						   <div style="padding: 20px;"> 
						   <div style="border-bottom: 1px solid #E75900; padding-bottom: 5px;">
						   <strong>
						   <font size="3"><a href="?execute=planesoperativo/reportes/reportes&method=default&Menu=F2&SubMenu=SF23#&p=1&s=25&sort=1&q=" onmouseover="this.style.color='#E75900'" onmouseout="this.style.color='#000000'">Reportes POA </a></font></strong>
						   </div>
						   <div>
						   <i>
					Permite descargar reportes, con opción de filtrado. 
						   </i>
						   </div>
						   </div>
						   
						   </td>
								
							</tr>
							
							
								<tr>
								
						   <td>
						   <div style="padding: 20px;"> 
						   <div style="border-bottom: 1px solid #E75900; padding-bottom: 5px;">
						   <strong>
						   <font size="3"><a href="?execute=planesoperativo/reportes/avances&method=default&Menu=F2&SubMenu=SF23#&p=1&s=25&sort=1&q=" onmouseover="this.style.color='#E75900'" onmouseout="this.style.color='#000000'">Reporte avances POA </a></font></strong>
						   </div>
						   <div>
						   <i>
					Permite descargar un reporte de los avances del Plan Operativo.
						   </i>
						   </div>
						   </div>
						   
						   </td>
								
							</tr>
							
							
							<tr>
								
						  <td>
						   <div style="padding: 20px;"> 
						   <div style="border-bottom: 1px solid #E75900; padding-bottom: 5px;">
						   <strong>
						   <font size="3"><a href="?execute=planesoperativo/reportes/comentarios&method=default&Menu=F2&SubMenu=SF23#&p=1&s=25&sort=1&q=" onmouseover="this.style.color='#E75900'" onmouseout="this.style.color='#000000'">Reporte comentarios POA</a></font></strong>
						   </div>
						   <div>
						   <i>
					Permite generar un reporte de comentarios del Plan Operativo. 
						   </i>
						   </div>
						   </div>
						   
						   </td>
								
							</tr>
							
							
							<tr>
								
						   <td>
						   <div style="padding: 20px;"> 
						   <div style="border-bottom: 1px solid #E75900; padding-bottom: 5px;">
						   <strong>
						   <font size="3"><a href="?execute=planesoperativo/reportes/evidencias&method=default&Menu=F2&SubMenu=SF23#&p=1&s=25&sort=1&q=" onmouseover="this.style.color='#E75900'" onmouseout="this.style.color='#000000'">Reporte de evidencias</a></font></strong>
						   </div>
						   <div>
						   <i>
					Genere reportes de evidencias del Plan Operativo.
						   </i>
						   </div>
						   </div>
						   
						   </td>
								
							</tr>
							
							
							<tr>
								
						   <td>
						   <div style="padding: 20px;"> 
						   <div style="border-bottom: 1px solid #E75900; padding-bottom: 5px;">
						   <strong>
						   <font size="3"><a href="?execute=planesoperativo/reportes/capturapoa&method=default&Menu=F2&SubMenu=SF23#&p=1&s=25&sort=1&q=" onmouseover="this.style.color='#E75900'" onmouseout="this.style.color='#000000'">Reporte de Estatus de Captura POA y entrega </a></font></strong>
						   </div>
						   <div>
						   <i>
					Genera reporte de estatus de captura y entrega del Plan Operativo.
						   </i>
						   </div>
						   </div>
						   
						   </td>
								
							</tr>
							
							
							<tr>
								
						   <td>
						   <div style="padding: 20px;"> 
						   <div style="border-bottom: 1px solid #E75900; padding-bottom: 5px;">
						   <strong>
						   <font size="3"><a href="?execute=planesoperativo/reportes/informes&method=default&Menu=F2&SubMenu=SF23#&p=1&s=25&sort=1&q=" onmouseover="this.style.color='#E75900'" onmouseout="this.style.color='#000000'">Reporte de estatus de captura informe y entrega</a></font></strong>
						   </div>
						   <div>
						   <i>
					Genere Reporte de estatus de captura informes y entregas.
						   </i>
						   </div>
						   </div>
						   
						   </td>
								
							</tr>
							
							
							<tr>
								
						   <td>
						   <div style="padding: 20px;"> 
						   <div style="border-bottom: 1px solid #E75900; padding-bottom: 5px;">
						   <strong>
						   <font size="3"><a href="?execute=planesoperativo/reportes/general&method=default&Menu=F2&SubMenu=SF23#&p=1&s=25&sort=1&q=" onmouseover="this.style.color='#E75900'" onmouseout="this.style.color='#000000'">Reporte Global de Campus</a></font></strong>
						   </div>
						   <div>
						   <i>
					 Reporte global de campus(POA)
						   </i>
						   </div>
						   </div>
						   
						   </td>
								
							</tr>
							
							
							<tr>
								
						   <td>
						   <div style="padding: 20px;"> 
						   <div style="border-bottom: 1px solid #E75900; padding-bottom: 5px;">
						   <strong>
						   <font size="3"><a href="?execute=planesoperativo/reportes/usuarios&method=default&Menu=F2&SubMenu=SF23#&p=1&s=25&sort=1&q=" onmouseover="this.style.color='#E75900'" onmouseout="this.style.color='#000000'">Reporte de Usuarios</a></font></strong>
						   </div>
						   <div>
						   <i>
					 Muestra un reporte de Usuarios Asignados en cada Plan.
						   </i>
						   </div>
						   </div>
						   
						   </td>
								
							</tr>
							
							
							<!--cambio i-->
							<tr>
								
						   <td>
						   <div style="padding: 20px;"> 
						   <div style="border-bottom: 1px solid #E75900; padding-bottom: 5px;">
						   <strong>
						   <font size="3"><a href="?execute=planesoperativo/reportes/generalavances&amp;method=default&amp;Menu=F2&amp;SubMenu=SF23#&amp;p=1&amp;s=25&amp;sort=1&amp;q=" onmouseover="this.style.color='#E75900'" onmouseout="this.style.color='#000000'">Reporte General Avances</a></font></strong>
						   </div>
						   <div>
						   <i>
					 Reporte General avances(POA)
						   </i>
						   </div>
						   </div>
						   
						   </td>
								
							</tr>
							
							<!--cambio f-->
							
							
							
							
							
						</table>
						</div>
					<!-- Table -->
						
						  <!-- Pagging -->
						
                        <div class="pagging" id="barfilterfooter">
                       
                     
                       <div class="search_pagination">
                       
                      
	                  </div>                       
                        
                        
                        </div>
						<!-- End Pagging -->
						
					
					
				</div>
				<!-- End Box -->
                
 