

<!-- Box -->
				<div class="box">
					<!-- Box Head -->
					<div class="box-head">
						<h1 class="left">Reportes Planes Operativo.</h1>
					<br>
						<BR>
					</div>
					<!-- End Box Head -->	
                    
                    
					<!-- Table -->
					<div  style="min-height: 300px;">
						<table width="100%"  border="0" cellspacing="0" cellpadding="0">
						
					  <!-- reportespoa-->
                        #REPORTESPOA#							
							
				    <!-- reportesavancespoa-->
                        #REPORTESAVANCESPOA#
						
					<!-- reportesavancespoa-->
                        #REPORTESCOMENTARIOSPOA#							
							
						<!-- reportesavancespoa-->
                        #REPORTESEVIDENCIASPOA#
						
						<!-- reportescapturapoa-->
                        #REPORTESCAPTURAPOA#
						
						
						<!-- reportesinformespoa-->
                        #REPORTESINFORMESPOA#
						
						
						<!-- reportesglobalpoa-->
                        #REPORTESGLOBALPOA#
						
						
						<!-- reportesusuariospoa-->
                        #REPORTESUSUARIOPOA#
						
						
							<!-- reportesgeneralavancespoa-->
                        #REPORTESGENERALPOA#
						
									
							
							
							
						</table>
						</div>
					<!-- Table -->
						
						  <!-- Pagging -->
						
                        <div class="pagging" id="barfilterfooter">
                       
                     
                       <div class="search_pagination">
                       
                      
	                  </div>                       
                        
                        
                        </div>
						<!-- End Pagging -->
						
					
					
				</div>
				<!-- End Box -->
                
 