

<!-- Box -->
				<div class="box">
					<!-- Box Head -->
					<div class="box-head">
						<h1 class="left">Reportes Planes Estratégicos.</h1>
					<br>
						<BR>
					</div>
					<!-- End Box Head -->	
                    
                    
                   
					<!-- Table -->
					<div  style="min-height: 300px;">
						<table width="100%"  border="0" cellspacing="0" cellpadding="0">
						
						
							
							
								<tr>
								
						   <td>
						   <div style="padding: 20px;"> 
						   <div style="border-bottom: 1px solid #E75900; padding-bottom: 5px;">
						   <strong>
						   <font size="3"><a href="?execute=planestrategico/reportes/reportes&method=default&Menu=F1&SubMenu=SF13#&p=1&s=25&sort=1&q=" onmouseover="this.style.color='#E75900'" onmouseout="this.style.color='#000000'">Reportes PE</a></font></strong>
						   </div>
						   <div>
						   <i>
					Esta funcionalidad le permite descargar reportes de Planes Estratégicos.
						   </i>
						   </div>
						   </div>
						   
						   </td>
								
							</tr>
							
							
							
							<tr>
								
						   <td>
						   <div style="padding: 20px;"> 
						   <div style="border-bottom: 1px solid #E75900; padding-bottom: 5px;">
						   <strong>
						   <font size="3"><a href="?execute=planestrategico/reportes/avances&method=default&Menu=F1&SubMenu=SF13#&p=1&s=25&sort=1&q=" onmouseover="this.style.color='#E75900'" onmouseout="this.style.color='#000000'">Reporte de Avances del Plan Estratégico</a></font></strong>
						   </div>
						   <div>
						   <i>
				  Genere un avances del Plan Estratégico.
						   </i>
						   </div>
						   </div>
						   
						   </td>
								
							</tr>
							
							
							
							
							<!--<tr>
								
						   <td>
						   <div style="padding: 20px;"> 
						   <div style="border-bottom: 1px solid #E75900; padding-bottom: 5px;">
						   <strong>
						   <font size="3"><a href="?execute=ayuda/soporte&method=default&Menu=F5&SubMenu=SF51#&p=1&s=25&sort=1&q=" onmouseover="this.style.color='#E75900'" onmouseout="this.style.color='#000000'">Reporte Global de Campus</a></font></strong>
						   </div>
						   <div>
						   <i>
					Reporte Global por Campus.
						   </i>
						   </div>
						   </div>
						   
						   </td>
								
							</tr>-->
							
							
						</table>
						</div>
					<!-- Table -->
						
						  <!-- Pagging -->
						
                        <div class="pagging" id="barfilterfooter">
                       
                     
                       <div class="search_pagination">
                       
                      
	                  </div>                       
                        
                        
                        </div>
						<!-- End Pagging -->
						
					
					
				</div>
				<!-- End Box -->
                
 