<!-- <script src="skins/default/js/roles/roles.js"></script>-->
 
 <!-- Alerta -->
<div id="alerta" class="alert alert-block " style="display:none;">
							<button type="button" class="close" data-dismiss="alert">×</button>
							<h4 id="headAlerta" class="alert-heading">!CORRECTO!</h4>
							<p><div id="bodyAlerta">El plan estrategico se ha guardado correctamente.</div></p>
</div>

<!--End Alerta -->
 
 

<!-- Box -->
				<div class="box">
					<!-- Box Head -->
					<div class="box-head">
						<h2 class="left">Herramientas del Sistema</h2>
					<br>
						<p>Puede administrar algunas funcionalidades del sistema. 
						
						</p>
					</div>
					<!-- End Box Head -->	
                    
                    
                   
				
                    
                    
					<!-- Table -->
					<div  style="min-height: 300px;">
						<table width="100%"  border="0" cellspacing="0" cellpadding="0">
							
						
							
							<tr>
								
						   <td>
						   <div style="padding: 20px;"> 
						   <div style="border-bottom: 1px solid #E75900; padding-bottom: 5px;">
						   <strong>
						   <font size="3"><a href="?execute=herramientas/registros&method=default&Menu=F3&SubMenu=SF35#&p=1&s=25&sort=1&q=" onmouseover="this.style.color='#E75900'" onmouseout="this.style.color='#000000'">Registros</a></font></strong>
						   </div>
						   <div>
						   <i>
					Registros y actividad del usuario en el sistema que se pueden filtrar en función del tipo de actividad y un intervalo de fechas. 
						   </i>
						   </div>
						   </div>
						   
						   </td>
								
							</tr>
							
							
							<tr>
								
						  <td>
						   <div style="padding: 20px;"> 
						   <div style="border-bottom: 1px solid #E75900; padding-bottom: 5px;">
						   <strong>
						   <font size="3"><a href="#" onmouseover="this.style.color='#E75900'" onmouseout="this.style.color='#000000'">Informes de error</a></font></strong>
						   </div>
						   <div>
						   <i>
					Registros y actividad del usuario en el sistema que se pueden filtrar en función del tipo de actividad y un intervalo de fechas. 
						   </i>
						   </div>
						   </div>
						   
						   </td>
								
							</tr>
							
							
							<tr>
								
						   <td>
						   <div style="padding: 20px;"> 
						   <div style="border-bottom: 1px solid #E75900; padding-bottom: 5px;">
						   <strong>
						   <font size="3"><a href="#" onmouseover="this.style.color='#E75900'" onmouseout="this.style.color='#000000'">Informes de estadísticas </a></font></strong>
						   </div>
						   <div>
						   <i>
					Ver informes de estadísticas que supervisan la actividad, el seguimiento de datos, las vistas de página y el uso, y proporcionan información de depuración. 
						   </i>
						   </div>
						   </div>
						   
						   </td>
								
							</tr>
							
							
							
							<tr>
								
						   <td>
						   <div style="padding: 20px;"> 
						   <div style="border-bottom: 1px solid #E75900; padding-bottom: 5px;">
						   <strong>
						   <font size="3"><a href="#" onmouseover="this.style.color='#E75900'" onmouseout="this.style.color='#000000'">Respaldos de sistema</a></font></strong>
						   </div>
						   <div>
						   <i>
					Respalda el sistema para poder elegir posteiormente un punto de restauración.
						   </i>
						   </div>
						   </div>
						   
						   </td>
								
							</tr>
							
							
							<tr>
								
						  <td>
						   <div style="padding: 20px;"> 
						   <div style="border-bottom: 1px solid #E75900; padding-bottom: 5px;">
						   <strong>
						   <font size="3"><a href="#" onmouseover="this.style.color='#E75900'" onmouseout="this.style.color='#000000'">Restauración  de sistema</a></font></strong>
						   </div>
						   <div>
						   <i>
					Restaura el sistema en un punto de restauración guardado.
						   </i>
						   </div>
						   </div>
						   
						   </td>
								
							</tr>
							
							
							<tr>
							
							<td>
						   <div style="padding: 20px;"> 
						   <div style="border-bottom: 1px solid #E75900; padding-bottom: 5px;">
						   <strong>
						   <font size="3"><a href="#" onmouseover="this.style.color='#E75900'" onmouseout="this.style.color='#000000'">Anuncios</a></font></strong>
						   </div>
						   <div>
						   <i>
					Permite crear anuncios de sistema para todos los usuarios activos.
						   </i>
						   </div>
						   </div>
						   
						   </td>
								
						
								
							</tr>
							
							
							
							<tr>
						<td>
						   <div style="padding: 20px;"> 
						   <div style="border-bottom: 1px solid #E75900; padding-bottom: 5px;">
						   <strong>
						   <font size="3"><a href="#" onmouseover="this.style.color='#E75900'" onmouseout="this.style.color='#000000'">Correo electrónico</a></font></strong>
						   </div>
						   <div>
						   <i>
					     Permite enviar correo electrónico a todos los usuarios del sistema. Tenga en cuenta que esta opción puede necesitar todos los recursos del sistema.


						   </i>
						   </div>
						   </div>
						   
						   </td>
						
								
							</tr>
							
							
							<tr>
						<td>
						   <div style="padding: 20px;"> 
						   <div style="border-bottom: 1px solid #E75900; padding-bottom: 5px;">
						   <strong>
						   <font size="3"><a href="#" onmouseover="this.style.color='#E75900'" onmouseout="this.style.color='#000000'">Notificaciones</a></font></strong>
						   </div>
						   <div>
						   <i>
					Desde esta página, el administrador del sistema puede definir la configuración de las notificaciones en lo referente al correo electrónico
						   </i>
						   </div>
						   </div>
						   
						   </td>
						
								
							</tr>
							
							
					
							
						</table>
						</div>
					<!-- Table -->
						
						  <!-- Pagging -->
						
                        <div class="pagging" id="barfilterfooter">
                       
                     
                       <div class="search_pagination">
                       
                      
	                  </div>                       
                        
                        
                        </div>
						<!-- End Pagging -->
						
					
					
				</div>
				<!-- End Box -->
                
 