<div id="image_BE087335-panel" class="detail_full result_image-panel search-image-border r1">

<div   class="full_layout_thumb-detail">

<div id="image_thumb_BE087335-panel" class="image_thumbnail">

<a id="enlargement_BE087335" onclick="#LINKRECURSO#" class="enlarge-image">

<img src="#IMAGEN#"  id="thumb_BE087335" class="search-results-image" >

</a>

</div>

</div>

<div class="full_layout_extend-detail"><div id="image_info_BE087335-panel">
<div id="title_detail_BE087335" class="full_layout_title-text full_layout-padding">
<span class="detail_title">#TITULO#</span></div></div>

<div class="full_layout-spacer">&nbsp;</div>
<div id="image_full_BE087335-panel">
<div id="collection_detail_BE087335" class="image_collection-text full_layout-padding"><span class="detail_label">Numero Resultados:</span><span class="notificatione green" >#NUMRESULTADOS#</span></div>

<div class="full_layout-spacer">&nbsp;</div>
<div id="model_release_detail_BE087335" class="image_modelrel-text full_layout-padding">
<span class="detail_label">Numero de Evidencias:</span><span class="notificatione">#NUMEVIDENCIAS#</span></div>
</div></div></div>