<div id="image_BE087335-panel" class="detail_full result_image-panel search-image-border r1">

<div class="full_layout_thumb-detail">

<div id="image_thumb_BE087335-panel" class="image_thumbnail">

<!--<a id="enlargement_BE087335" href="/stock-photo/rights-managed/BE087335/detail-of-woman-with-collar-from-a" class="enlarge-image">-->
<div  class="image_thumbnail"><a id="enlargement_42-35185762"  href="#" onclick="#LINKRECURSO#" class="enlarge-image">

<img src="#IMAGEN#" id="thumb_BE087335" class="search-results-image" >

</a>
</div>

</div>

<div  class="result_image-panel search-image-border">
	
	
	<div id="image_details_42-35185762-panel" class="image_detail-panel">
        <div id="action_42-35185762-panel">
          <div id="rfcd_42-35185762-panel" class="rfcd-panel">
            <div class="rmrs-icon">
              <div class="rmrs-label">#FORMATO# </div>
            </div>
            <!--<span style="position:absolute; margin:4px 4px; width:50px;">#ID# *</span>-->
 
          </div>
          <div id="icon_42-35185762-panel" class="icons-container">
           
		   <!--#LINKEDIT#-->
			
		
			
			<!--#LINKDELETE#-->
		   
          </div>
        </div>
        <div id="info_42-35185762-panel" class="image_details-panel">
          <div id="details_42-35185762-panel">
         
           <!-- <div id="" class="image_title-text" alt="titulo">#TITULO#</div>-->
           <!-- <div id="" class="image_date_photo-text">#FECHA#</div>-->
          </div>
        </div>
      </div>
</div>




</div>



 <!--<div  class="image_thumbnail"><a id="enlargement_42-35185762"  href="#" onclick="#LINKRECURSO#" class="enlarge-image"><img src="#IMAGEN#" id="thumb_42-35185762" class="search-results-image"></a>
      
      
        <div style="display:none;" id="visualsearch_42-35185762-action" class="action-link link mlt_container"><a class="mlt_link" href="#">Más imágenes como ésta</a></div>
      </div>-->
      

<div class="full_layout_extend-detail"><div id="image_info_BE087335-panel">
<div id="title_detail_BE087335" class="full_layout_title-text full_layout-padding">
<span class="detail_title">#TITULO#</span></div></div>

<div class="full_layout-spacer">&nbsp;</div>
<div id="image_full_BE087335-panel">
<div class="full_layout-spacer">&nbsp;</div>
<div id="collection_detail_BE087335" class="image_collection-text full_layout-padding"><span class="detail_label"><strong>Objetivo Estratégico:</strong> </span>#OBJETOVOE#</div>

<div class="full_layout-spacer">&nbsp;</div>

<div id="collection_detail_BE087335" class="image_collection-text full_layout-padding"><span class="detail_label"><strong>Resultado:</strong> </span>#RESULTADO#</div>

<div class="full_layout-spacer">&nbsp;</div>
<div id="model_release_detail_BE087335" class="image_modelrel-text full_layout-padding">
<span class="detail_label"><strong>Evidencia:</strong></span>#EVIDENCIA#</div>
</div></div></div>








