

<!-- Box -->
				<div class="box">
					<!-- Box Head -->
					<div class="box-head">
						<h1 class="left">Soporte, Guía y Manuales.</h1>
					<br>
						<BR>
					</div>
					<!-- End Box Head -->	
                    
                    
                   
				
                    
                    
					<!-- Table -->
					<div  style="min-height: 300px;">
						<table width="100%"  border="0" cellspacing="0" cellpadding="0">
						
						<tr>
								
						   <td>
						   <div style="padding: 20px;"> 
						   <div style="border-bottom: 1px solid #E75900; padding-bottom: 5px;">
						   <strong>
						   <font size="3"><a href="?execute=ayuda/guia&method=default&Menu=F5&SubMenu=SF51#&p=1&s=25&sort=1&q=" onmouseover="this.style.color='#E75900'" onmouseout="this.style.color='#000000'">Guía rápida</a></font></strong>
						   </div>
						   <div>
						   <i>
					Guía Rapida para la operación del Sistema de Planeación de la Red de Universidades Anáhuac.
						   </i>
						   </div>
						   </div>
						   
						   </td>
								
							</tr>
							
							
								<tr>
								
						   <td>
						   <div style="padding: 20px;"> 
						   <div style="border-bottom: 1px solid #E75900; padding-bottom: 5px;">
						   <strong>
						   <font size="3"><a href="?execute=ayuda/buscador&method=default&Menu=F5&SubMenu=SF51#&p=1&s=25&sort=1&q=" onmouseover="this.style.color='#E75900'" onmouseout="this.style.color='#000000'">Buscador</a></font></strong>
						   </div>
						   <div>
						   <i>
					Esta funcionalidad le permite al usuario, buscar cocneptos.
						   </i>
						   </div>
						   </div>
						   
						   </td>
								
							</tr>
							
							
							<tr>
								
						  <td>
						   <div style="padding: 20px;"> 
						   <div style="border-bottom: 1px solid #E75900; padding-bottom: 5px;">
						   <strong>
						   <font size="3"><a href="?execute=ayuda/preguntas&method=default&Menu=F5&SubMenu=SF51#&p=1&s=25&sort=1&q=" onmouseover="this.style.color='#E75900'" onmouseout="this.style.color='#000000'">Preguntas Frecuentes</a></font></strong>
						   </div>
						   <div>
						   <i>
					Muestra un listado de las preguntas frecuentes que se les presentan al Usuario. 
						   </i>
						   </div>
						   </div>
						   
						   </td>
								
							</tr>
							
							
							<tr>
								
						   <td>
						   <div style="padding: 20px;"> 
						   <div style="border-bottom: 1px solid #E75900; padding-bottom: 5px;">
						   <strong>
						   <font size="3"><a href="?execute=ayuda/directorio&method=default&Menu=F5&SubMenu=SF51#&p=1&s=25&sort=1&q=" onmouseover="this.style.color='#E75900'" onmouseout="this.style.color='#000000'">Directorio por Temas</a></font></strong>
						   </div>
						   <div>
						   <i>
					Listado de temas de ayuda del Sistema de Planeación.
						   </i>
						   </div>
						   </div>
						   
						   </td>
								
							</tr>
							
							
							<tr>
								
						   <td>
						   <div style="padding: 20px;"> 
						   <div style="border-bottom: 1px solid #E75900; padding-bottom: 5px;">
						   <strong>
						   <font size="3"><a href="?execute=ayuda/glosario&method=default&Menu=F5&SubMenu=SF51#&p=1&s=25&sort=1&q=" onmouseover="this.style.color='#E75900'" onmouseout="this.style.color='#000000'">Glosario </a></font></strong>
						   </div>
						   <div>
						   <i>
					Lista de terminos que se utilizan en todo el Sistema de Planeación.
						   </i>
						   </div>
						   </div>
						   
						   </td>
								
							</tr>
							
							
							<tr>
								
						   <td>
						   <div style="padding: 20px;"> 
						   <div style="border-bottom: 1px solid #E75900; padding-bottom: 5px;">
						   <strong>
						   <font size="3"><a href="?execute=ayuda/soporte&method=default&Menu=F5&SubMenu=SF51#&p=1&s=25&sort=1&q=" onmouseover="this.style.color='#E75900'" onmouseout="this.style.color='#000000'">Soporte</a></font></strong>
						   </div>
						   <div>
						   <i>
					Opcioón para crear un caso de ayuda y un asesor atenderá su solicitud.
						   </i>
						   </div>
						   </div>
						   
						   </td>
								
							</tr>
							
							
						</table>
						</div>
					<!-- Table -->
						
						  <!-- Pagging -->
						
                        <div class="pagging" id="barfilterfooter">
                       
                     
                       <div class="search_pagination">
                       
                      
	                  </div>                       
                        
                        
                        </div>
						<!-- End Pagging -->
						
					
					
				</div>
				<!-- End Box -->
                
 