 <script src="skins/default/js/planestrategico/previewplan.js"></script>


<div id="alerta" class="alert alert-block " style="display:none;">
							<button type="button" class="close" data-dismiss="alert">×</button>
							<h4 id="headAlerta" class="alert-heading">!CORRECTO!</h4>
							<p><div id="bodyAlerta">El plan estrategico se ha guardado correctamente.</div></p>
</div>


				<div class="box">
					<!-- Box Head -->
					<div class="box-head">
						<h1 class="left">#TITULO#</h1><br>
						
						
					</div>
					<!-- End Box Head -->	
             
                    
                    <!-- Pagging -->
						
                     
                      
                        <div class="pagging">
                         <div class="left" id="menucontent">
                       
                       <ul class="subMenu" style="margin-top:15px;">
                       <li class="active"><a href="#">L&iacute;neas y Objetivos</a></li>
                       <li> <a href="#MENUURL#">Documentos Adjuntos</a></li>
                     
                       </ul>
                       
						 </div>
                        <div class="right">
                        
						
						#COMPARTIR#
						
                        #IMPRIMIR#
                        
						#EXPORTAR#
						
                        
                        <a href="?execute=principal&method=default&Menu=F1&SubMenu=SF11#&p=1&s=25&sort=1&q=" class="btn btn-large"><i class="icon-chevron-left"></i> Regresar</a>
                         
					
                        </div>
                        
						</div>
              
						<!-- End Pagging -->
						
                    
                    
					<!-- Table -->
					<div class="box-content">
                   
                       
						<div class="form-horizontal">
						
                          #LINEAS#
                     
						</div>   

					</div>
					<!-- Table -->
					
					
					 <!-- Pagging -->
						
                        <div class="pagging" style="border-top:1px solid #BBBBBB;">
              		
                        <div class="right">
                        <a href="?execute=principal&method=default&Menu=F1&SubMenu=SF11#&p=1&s=25&sort=1&q=" class="btn btn-large"><i class=" icon-chevron-left"></i> Regresar</a>
						
                        </div>
                        
						</div>
              
						<!-- End Pagging -->
					
					
				</div>
				<!-- End Box -->           
                  